-- Baseline of the schema Hibernate had been generating with ddl-auto=update.
-- From here on the schema is owned by these migrations and Hibernate only validates it.

create table users (
    id            bigint generated by default as identity primary key,
    name          varchar(120) not null,
    email         varchar(180) not null,
    password_hash varchar(255) not null,
    created_at    timestamp(6) with time zone not null,
    constraint uk_users_email unique (email)
);

create table burger_joints (
    id             bigint generated by default as identity primary key,
    name           varchar(150) not null,
    address        varchar(250) not null,
    area           varchar(100),
    photo_url      varchar(500),
    latitude       double precision,
    longitude      double precision,
    place_id       varchar(300),
    last_synced_at timestamp(6) with time zone,
    constraint uk_burger_joints_place_id unique (place_id)
);

create table ratings (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null,
    burger_joint_id bigint not null,
    score           integer not null,
    comment         varchar(1000),
    created_at      timestamp(6) with time zone not null,
    constraint uk_ratings_user_joint unique (user_id, burger_joint_id),
    constraint fk_ratings_user foreign key (user_id) references users (id),
    constraint fk_ratings_burger_joint foreign key (burger_joint_id) references burger_joints (id)
);

create table wishlist_items (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null,
    burger_joint_id bigint not null,
    created_at      timestamp(6) with time zone not null,
    constraint uk_wishlist_user_joint unique (user_id, burger_joint_id),
    constraint fk_wishlist_user foreign key (user_id) references users (id),
    constraint fk_wishlist_burger_joint foreign key (burger_joint_id) references burger_joints (id)
);

create table places_api_usage (
    id         bigint generated by default as identity primary key,
    year_month varchar(7) not null,
    call_type  varchar(20) not null,
    call_count integer not null,
    constraint uk_places_usage_month_type unique (year_month, call_type),
    constraint ck_places_usage_call_type check (call_type in ('SEARCH', 'PHOTO'))
);
