alter table users add column email_verified boolean not null default false;

-- The accounts that already exist predate verification. Leaving them unverified
-- would lock out real people for a rule that did not exist when they signed up.
update users set email_verified = true;

-- One table for both flows: the mechanics are identical (a short-lived code sent
-- by email), only what it authorises differs.
create table verification_codes (
    id          bigint generated by default as identity primary key,
    user_id     bigint not null,
    purpose     varchar(30) not null,
    -- Hashed, never stored in the clear: a leaked database must not hand over
    -- the ability to take over accounts.
    code_hash   varchar(255) not null,
    expires_at  timestamp(6) with time zone not null,
    attempts    integer not null,
    consumed_at timestamp(6) with time zone,
    created_at  timestamp(6) with time zone not null,
    constraint fk_verification_codes_user foreign key (user_id) references users (id) on delete cascade,
    constraint ck_verification_codes_purpose check (purpose in ('EMAIL_VERIFICATION', 'PASSWORD_RESET'))
);

-- Every lookup is "the newest live code for this user and purpose".
create index ix_verification_codes_user_purpose on verification_codes (user_id, purpose, created_at desc);
