-- La sesión pasa a vivir en cookies HttpOnly. El access token sigue siendo un JWT
-- corto, pero un JWT no se puede revocar: mientras no venza, vale. El refresh token
-- se guarda acá justamente para poder cortarlo.
create table refresh_tokens (
    id         bigint generated by default as identity primary key,
    user_id    bigint not null,
    -- SHA-256 en hexadecimal, no BCrypt: hay que buscar el token por su hash, así que
    -- el hash tiene que ser determinístico. Con 256 bits de aleatoriedad la fuerza
    -- bruta no es el riesgo que hay que cubrir; leer la base sí.
    token_hash varchar(64) not null,
    expires_at timestamp(6) with time zone not null,
    revoked_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone not null,
    constraint uk_refresh_tokens_hash unique (token_hash),
    constraint fk_refresh_tokens_user foreign key (user_id) references users (id) on delete cascade
);

-- Para revocar de una todos los tokens de una persona, que es la reacción cuando
-- aparece uno reusado.
create index ix_refresh_tokens_user on refresh_tokens (user_id);

-- Para la limpieza periódica de los que ya no sirven.
create index ix_refresh_tokens_expires_at on refresh_tokens (expires_at);
